name: boton_panico_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_sound: ^9.2.13
  geolocator: ^10.1.0
  http: ^1.1.0
  image: ^4.1.7
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/logo.png
    - assets/imgs/background.jpg
    - assets/imgs/background-login.jpg
    - assets/imgs/muni_logo.png
    - assets/imgs/logo-default.png
    - assets/imgs/logo.png
    - assets/imgs/boton-panico.png
    - assets/imgs/boton-panico1.png